name: build cpp
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build_cpp:
    runs-on: ubuntu-latest
    
    steps:
      - name: ls
        run: ls -la
        
      - uses: actions/checkout@v3
      
      - name: env report
        run: |
          ls -la
          printenv
        
      - name: build
        run: |
          g++ hello.cpp -o hello.o
          
