name: build cpp
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build_cpp:
    runs-on: windows-latest
    
    steps:
      - name: ls
        run: ls -la
        
      - uses: actions/checkout@v3
      
      - name: env report
        run: |
          ls -la
          printenv
        
      - name: build
        run: |
          cl /EMsc hello.cpp
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: cpp_app
          path: hello.exe
          retention-days: 5
